-- Generated by scripts/clean_and_seed.py. Re-run that script after editing raw CSVs.
drop view if exists public.association_vendor_counts;
drop table if exists public.data_quality_flags, public.association_vendors, public.vendor_aliases, public.vendors, public.board_members, public.associations cascade;

create extension if not exists citext;

create table if not exists public.associations (
    id bigint generated by default as identity primary key,
    hoa_code text not null unique check (hoa_code ~ '^SR-[0-9]{2}$'),
    association_name text not null,
    city text not null,
    state_code char(2) not null check (state_code ~ '^[A-Z]{2}$'),
    unit_count integer check (unit_count is null or unit_count > 0),
    monthly_dues numeric(10,2) check (monthly_dues is null or monthly_dues >= 0),
    fiscal_year_end_month smallint check (
        fiscal_year_end_month is null or fiscal_year_end_month between 1 and 12
    ),
    reserve_balance numeric(14,2) check (
        reserve_balance is null or reserve_balance >= 0
    ),
    last_reserve_study date,
    last_reserve_study_precision text not null default 'unknown'
        check (last_reserve_study_precision in ('day', 'month', 'unknown')),
    has_reserve_study boolean not null default false,
    board_email citext,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create table if not exists public.board_members (
    id bigint generated by default as identity primary key,
    association_id bigint not null references public.associations(id) on delete cascade,
    full_name text not null,
    role text not null,
    email citext,
    term_start date,
    term_end date,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    check (term_end is null or term_start is null or term_end >= term_start)
);

create unique index if not exists board_members_natural_key
    on public.board_members (
        association_id,
        lower(full_name),
        lower(role),
        coalesce(term_start, date '1900-01-01')
    );

create table if not exists public.vendors (
    id bigint generated by default as identity primary key,
    canonical_key text not null unique,
    canonical_name text not null,
    trade text not null,
    phone_e164 text,
    phone_display text,
    email citext,
    coi_on_file boolean,
    service_area text[] not null default '{}',
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create index if not exists vendors_trade_idx on public.vendors (trade);
create index if not exists vendors_email_idx on public.vendors (email);

create table if not exists public.vendor_aliases (
    id bigint generated by default as identity primary key,
    vendor_id bigint not null references public.vendors(id) on delete cascade,
    alias_name text not null,
    source_file text not null default 'vendors_intake.csv',
    created_at timestamptz not null default now()
);

create unique index if not exists vendor_aliases_vendor_alias_key
    on public.vendor_aliases (vendor_id, lower(alias_name));

create table if not exists public.association_vendors (
    association_id bigint not null references public.associations(id) on delete cascade,
    vendor_id bigint not null references public.vendors(id) on delete cascade,
    relationship_status text not null default 'active'
        check (relationship_status in ('active', 'prospect', 'inactive')),
    source_file text not null default 'vendors_intake.csv',
    created_at timestamptz not null default now(),
    primary key (association_id, vendor_id)
);

create table if not exists public.data_quality_flags (
    id bigint generated by default as identity primary key,
    entity_type text not null,
    entity_key text not null,
    field_name text not null,
    raw_value text,
    cleaned_value text,
    issue text not null,
    severity text not null default 'review'
        check (severity in ('info', 'review', 'warning')),
    created_at timestamptz not null default now()
);

create index if not exists data_quality_flags_entity_idx
    on public.data_quality_flags (entity_type, entity_key);

create or replace view public.association_vendor_counts as
select
    a.id as association_id,
    a.hoa_code,
    v.trade,
    count(*)::integer as vendor_count
from public.associations a
join public.association_vendors av on av.association_id = a.id
join public.vendors v on v.id = av.vendor_id
group by a.id, a.hoa_code, v.trade;


truncate table public.data_quality_flags, public.association_vendors, public.vendor_aliases, public.vendors, public.board_members, public.associations restart identity cascade;

insert into public.associations (hoa_code, association_name, city, state_code, unit_count, monthly_dues, fiscal_year_end_month, reserve_balance, last_reserve_study, last_reserve_study_precision, has_reserve_study, board_email) values
('SR-01', 'Maplewood Terrace Owners Association', 'Riverton', 'CA', 48, 285.00, 12, 142500.00, '2023-04-12', 'day', TRUE, 'board@maplewoodterrace.example'),
('SR-02', 'Cedar Hollow Condominiums, Inc.', 'Lakeside', 'CA', NULL, 310.00, 12, 98750.00, '2022-04-01', 'month', TRUE, 'cedarhollowhoa@example.com'),
('SR-03', 'Sunfield Villas HOA', 'Riverton', 'CA', 72, 340.00, 12, NULL, NULL, 'unknown', FALSE, NULL),
('SR-04', 'The Beacon Pointe Association', 'Bay Harbor', 'CA', 120, 415.00, 6, 512000.00, '2024-03-01', 'month', TRUE, 'info@beaconpointe.example'),
('SR-05', 'Orchard Glen Homeowners Assn', 'Lakeside', 'CA', 36, 255.00, 12, 61200.00, '2021-09-01', 'day', TRUE, 'board@orchardglen.example'),
('SR-06', 'Stonebridge Commons', 'Bay Harbor', 'CA', NULL, 0.00, 12, NULL, NULL, 'unknown', FALSE, 'stonebridge@example.com'),
('SR-07', 'Harborview Heights Owners Association, Inc.', 'Bay Harbor', 'CA', 94, 390.00, 12, 378900.00, '2024-01-15', 'day', TRUE, 'hello@harborviewheights.example'),
('SR-08', 'Willow Creek Estates', 'Greenvale', 'CA', 28, 220.00, 3, 44000.00, '2020-06-30', 'day', TRUE, NULL),
('SR-09', 'Pinecrest Gardens Condo Assoc.', 'Greenvale', 'CA', 55, 300.00, 12, NULL, NULL, 'unknown', FALSE, 'pinecrest@example.com'),
('SR-10', 'Lantern Bay Community Association', 'Bay Harbor', 'CA', 140, 460.00, 9, 690250.00, '2023-11-20', 'day', TRUE, 'board@lanternbay.example'),
('SR-11', 'Aspen Ridge HOA', 'Riverton', 'CA', 40, 275.00, 12, 88000.00, '2022-02-14', 'day', TRUE, 'aspenridge@example.com'),
('SR-12', 'Tidewater Townhomes Owners Assn', 'Lakeside', 'CA', 66, 355.00, NULL, 201400.00, '2024-03-05', 'day', TRUE, NULL);

insert into public.board_members (association_id, full_name, role, email, term_start, term_end) values
((select id from public.associations where hoa_code = 'SR-01'), 'Alex Tanaka', 'President', 'alex.tanaka@example.com', '2023-07-01', '2025-07-01'),
((select id from public.associations where hoa_code = 'SR-01'), 'Reese Patel', 'Vice President', 'reese.patel@example.com', '2024-01-01', NULL),
((select id from public.associations where hoa_code = 'SR-01'), 'Alex Nguyen', 'Treasurer', NULL, '2023-07-01', '2026-01-01'),
((select id from public.associations where hoa_code = 'SR-02'), 'Reese Webb', 'President', 'reese.webb@example.com', '2024-06-15', '2025-07-01'),
((select id from public.associations where hoa_code = 'SR-02'), 'Jamie Flores', 'Vice President', 'jamie.flores@example.com', '2024-01-01', '2025-07-01'),
((select id from public.associations where hoa_code = 'SR-02'), 'Reese Brooks', 'Treasurer', 'reese.brooks@example.com', '2023-07-01', '2025-07-01'),
((select id from public.associations where hoa_code = 'SR-02'), 'Skyler Reyes', 'Secretary', NULL, '2024-06-15', '2026-01-01'),
((select id from public.associations where hoa_code = 'SR-02'), 'Taylor Silva', 'Member at Large', 'taylor.silva@example.com', '2025-01-01', '2026-01-01'),
((select id from public.associations where hoa_code = 'SR-03'), 'Drew Patel', 'President', 'drew.patel@example.com', '2024-06-15', '2026-01-01'),
((select id from public.associations where hoa_code = 'SR-03'), 'Drew Johnson', 'Vice President', 'drew.johnson@example.com', '2025-01-01', '2025-07-01'),
((select id from public.associations where hoa_code = 'SR-03'), 'Reese Patel', 'Treasurer', NULL, '2023-07-01', NULL),
((select id from public.associations where hoa_code = 'SR-03'), 'Jordan Silva', 'Secretary', 'jordan.silva@example.com', '2024-01-01', NULL),
((select id from public.associations where hoa_code = 'SR-03'), 'Riley Cole', 'Member at Large', 'riley.cole@example.com', '2025-01-01', '2025-07-01'),
((select id from public.associations where hoa_code = 'SR-04'), 'Taylor Kim', 'President', 'taylor.kim@example.com', '2024-01-01', '2025-07-01'),
((select id from public.associations where hoa_code = 'SR-04'), 'Drew Tanaka', 'Vice President', 'drew.tanaka@example.com', '2024-06-15', NULL),
((select id from public.associations where hoa_code = 'SR-04'), 'Riley Hughes', 'Treasurer', 'riley.hughes@example.com', '2023-07-01', NULL),
((select id from public.associations where hoa_code = 'SR-04'), 'Devon Okafor', 'Secretary', 'devon.okafor@example.com', '2023-07-01', '2026-01-01'),
((select id from public.associations where hoa_code = 'SR-04'), 'Skyler Reyes', 'Member at Large', 'skyler.reyes@example.com', '2024-01-01', '2025-07-01'),
((select id from public.associations where hoa_code = 'SR-05'), 'Morgan Webb', 'President', 'morgan.webb@example.com', '2024-06-15', '2025-07-01'),
((select id from public.associations where hoa_code = 'SR-05'), 'Riley Garcia', 'Vice President', 'riley.garcia@example.com', '2025-01-01', NULL),
((select id from public.associations where hoa_code = 'SR-05'), 'Harper Flores', 'Treasurer', 'harper.flores@example.com', '2023-07-01', '2025-07-01'),
((select id from public.associations where hoa_code = 'SR-05'), 'Drew Cole', 'Secretary', NULL, '2024-01-01', '2026-01-01'),
((select id from public.associations where hoa_code = 'SR-05'), 'Casey Webb', 'Member at Large', 'casey.webb@example.com', '2024-06-15', '2026-01-01'),
((select id from public.associations where hoa_code = 'SR-06'), 'Sam Flores', 'President', 'sam.flores@example.com', '2025-01-01', '2026-01-01'),
((select id from public.associations where hoa_code = 'SR-06'), 'Avery Tanaka', 'Vice President', NULL, '2025-01-01', NULL),
((select id from public.associations where hoa_code = 'SR-06'), 'Jordan Johnson', 'Treasurer', 'jordan.johnson@example.com', '2024-06-15', '2026-01-01'),
((select id from public.associations where hoa_code = 'SR-06'), 'Reese Hughes', 'Secretary', 'reese.hughes@example.com', '2023-07-01', '2026-01-01'),
((select id from public.associations where hoa_code = 'SR-06'), 'Devon Webb', 'Member at Large', 'devon.webb@example.com', '2023-07-01', '2025-07-01'),
((select id from public.associations where hoa_code = 'SR-07'), 'Skyler Garcia', 'President', 'skyler.garcia@example.com', '2024-01-01', NULL),
((select id from public.associations where hoa_code = 'SR-07'), 'Jamie Nguyen', 'Vice President', NULL, '2025-01-01', NULL),
((select id from public.associations where hoa_code = 'SR-07'), 'Morgan Nguyen', 'Treasurer', 'morgan.nguyen@example.com', '2024-01-01', '2026-01-01'),
((select id from public.associations where hoa_code = 'SR-07'), 'Reese Cole', 'Secretary', 'reese.cole@example.com', '2023-07-01', '2025-07-01'),
((select id from public.associations where hoa_code = 'SR-07'), 'Avery Cole', 'Member at Large', 'avery.cole@example.com', '2023-07-01', NULL),
((select id from public.associations where hoa_code = 'SR-08'), 'Morgan Hughes', 'President', 'morgan.hughes@example.com', '2023-07-01', NULL),
((select id from public.associations where hoa_code = 'SR-08'), 'Sam Webb', 'Vice President', 'sam.webb@example.com', '2024-06-15', NULL),
((select id from public.associations where hoa_code = 'SR-08'), 'Jordan Kim', 'Treasurer', 'jordan.kim@example.com', '2025-01-01', '2026-01-01'),
((select id from public.associations where hoa_code = 'SR-08'), 'Quinn Ramos', 'Secretary', 'quinn.ramos@example.com', '2023-07-01', '2026-01-01'),
((select id from public.associations where hoa_code = 'SR-08'), 'Jordan Tanaka', 'Member at Large', 'jordan.tanaka@example.com', '2023-07-01', '2026-01-01'),
((select id from public.associations where hoa_code = 'SR-09'), 'Devon Reyes', 'President', NULL, '2023-07-01', NULL),
((select id from public.associations where hoa_code = 'SR-09'), 'Avery Cole', 'Vice President', 'avery.cole@example.com', '2023-07-01', NULL),
((select id from public.associations where hoa_code = 'SR-09'), 'Morgan Okafor', 'Treasurer', 'morgan.okafor@example.com', '2024-06-15', '2025-07-01'),
((select id from public.associations where hoa_code = 'SR-10'), 'Jordan Webb', 'President', 'jordan.webb@example.com', '2024-06-15', NULL),
((select id from public.associations where hoa_code = 'SR-10'), 'Jamie Silva', 'Vice President', 'jamie.silva@example.com', '2024-01-01', '2026-01-01'),
((select id from public.associations where hoa_code = 'SR-10'), 'Sam Tanaka', 'Treasurer', 'sam.tanaka@example.com', '2024-01-01', '2025-07-01'),
((select id from public.associations where hoa_code = 'SR-11'), 'Morgan Ramos', 'President', 'morgan.ramos@example.com', '2024-06-15', '2025-07-01'),
((select id from public.associations where hoa_code = 'SR-11'), 'Riley Cole', 'Vice President', 'riley.cole@example.com', '2024-01-01', NULL),
((select id from public.associations where hoa_code = 'SR-11'), 'Skyler Silva', 'Treasurer', 'skyler.silva@example.com', '2024-01-01', '2026-01-01'),
((select id from public.associations where hoa_code = 'SR-11'), 'Avery Ramos', 'Secretary', 'avery.ramos@example.com', '2024-01-01', '2025-07-01'),
((select id from public.associations where hoa_code = 'SR-11'), 'Casey Brooks', 'Member at Large', 'casey.brooks@example.com', '2023-07-01', NULL),
((select id from public.associations where hoa_code = 'SR-12'), 'Casey Brooks', 'President', NULL, '2024-06-15', NULL),
((select id from public.associations where hoa_code = 'SR-12'), 'Harper Okafor', 'Vice President', 'harper.okafor@example.com', '2025-01-01', NULL),
((select id from public.associations where hoa_code = 'SR-12'), 'Reese Tanaka', 'Treasurer', 'reese.tanaka@example.com', '2024-06-15', '2025-07-01')
on conflict do nothing;

insert into public.vendors (canonical_key, canonical_name, trade, phone_e164, phone_display, email, coi_on_file, service_area) values
('email:estimates@titanpaving.example', 'Titan Paving', 'Asphalt/Paving', '+15552456610', '(555) 245-6610', 'estimates@titanpaving.example', FALSE, ARRAY['Bay Harbor']::text[]),
('email:office@reliableelec.example', 'Reliable Electric', 'Electrical', '+15559094521', '(555) 909-4521', 'office@reliableelec.example', TRUE, ARRAY['Riverton']::text[]),
('email:contact@brightpathscapes.example', 'Bright Path Landscaping', 'Landscaping', '+15552013344', '(555) 201-3344', 'contact@brightpathscapes.example', TRUE, ARRAY['Bay Harbor', 'Riverton']::text[]),
('email:book@greenleafpest.example', 'GreenLeaf Pest Control', 'Pest Control', '+15556107733', '(555) 610-7733', 'book@greenleafpest.example', TRUE, ARRAY['Greenvale', 'Lakeside']::text[]),
('email:dispatch@coastlineplumb.example', 'Coastline Plumbing', 'Plumbing', '+15558801290', '(555) 880-1290', 'dispatch@coastlineplumb.example', TRUE, ARRAY['Bay Harbor']::text[]),
('email:service@aquapro.example', 'AquaPro Pool Service', 'Pool Maintenance', '+15553321188', '(555) 332-1188', 'service@aquapro.example', TRUE, ARRAY['Bay Harbor', 'Lakeside']::text[]),
('email:jobs@summitroof.example', 'Summit Roofing', 'Roofing', '+15557770042', '(555) 777-0042', 'jobs@summitroof.example', FALSE, ARRAY[]::text[]),
('email:dispatch@anchorsecurity.example', 'Anchor Security Patrol', 'Security', '+15557009090', '(555) 700-9090', 'dispatch@anchorsecurity.example', TRUE, ARRAY['Bay Harbor']::text[]),
('email:hello@evergreentree.example', 'Evergreen Tree Care', 'Tree Service', '+15554429981', '(555) 442-9981', 'hello@evergreentree.example', FALSE, ARRAY['Greenvale']::text[]),
('email:info@clearviewwc.example', 'ClearView Window Cleaning', 'Window Cleaning', '+15551182200', '(555) 118-2200', 'info@clearviewwc.example', TRUE, ARRAY[]::text[]);

insert into public.vendor_aliases (vendor_id, alias_name) values
((select id from public.vendors where canonical_key = 'email:book@greenleafpest.example'), 'GreenLeaf Pest Control'),
((select id from public.vendors where canonical_key = 'email:contact@brightpathscapes.example'), 'Bright Path Landscaping'),
((select id from public.vendors where canonical_key = 'email:contact@brightpathscapes.example'), 'Bright Path Landscaping LLC'),
((select id from public.vendors where canonical_key = 'email:dispatch@anchorsecurity.example'), 'Anchor Security Patrol'),
((select id from public.vendors where canonical_key = 'email:dispatch@coastlineplumb.example'), 'Coastline Plumbing'),
((select id from public.vendors where canonical_key = 'email:estimates@titanpaving.example'), 'Titan Paving'),
((select id from public.vendors where canonical_key = 'email:hello@evergreentree.example'), 'Evergreen Tree Care'),
((select id from public.vendors where canonical_key = 'email:info@clearviewwc.example'), 'ClearView Window Cleaning'),
((select id from public.vendors where canonical_key = 'email:jobs@summitroof.example'), 'Summit Roofing Co.'),
((select id from public.vendors where canonical_key = 'email:office@reliableelec.example'), 'Reliable Electric'),
((select id from public.vendors where canonical_key = 'email:office@reliableelec.example'), 'Reliable Electrical Services'),
((select id from public.vendors where canonical_key = 'email:service@aquapro.example'), 'AquaPro Pool Service')
on conflict do nothing;

insert into public.association_vendors (association_id, vendor_id, relationship_status) values
((select id from public.associations where hoa_code = 'SR-01'), (select id from public.vendors where canonical_key = 'email:contact@brightpathscapes.example'), 'active'),
((select id from public.associations where hoa_code = 'SR-01'), (select id from public.vendors where canonical_key = 'email:office@reliableelec.example'), 'active'),
((select id from public.associations where hoa_code = 'SR-04'), (select id from public.vendors where canonical_key = 'email:contact@brightpathscapes.example'), 'active'),
((select id from public.associations where hoa_code = 'SR-04'), (select id from public.vendors where canonical_key = 'email:dispatch@anchorsecurity.example'), 'active'),
((select id from public.associations where hoa_code = 'SR-04'), (select id from public.vendors where canonical_key = 'email:dispatch@coastlineplumb.example'), 'active'),
((select id from public.associations where hoa_code = 'SR-04'), (select id from public.vendors where canonical_key = 'email:estimates@titanpaving.example'), 'active'),
((select id from public.associations where hoa_code = 'SR-07'), (select id from public.vendors where canonical_key = 'email:contact@brightpathscapes.example'), 'active'),
((select id from public.associations where hoa_code = 'SR-07'), (select id from public.vendors where canonical_key = 'email:dispatch@coastlineplumb.example'), 'active'),
((select id from public.associations where hoa_code = 'SR-10'), (select id from public.vendors where canonical_key = 'email:contact@brightpathscapes.example'), 'active'),
((select id from public.associations where hoa_code = 'SR-10'), (select id from public.vendors where canonical_key = 'email:dispatch@anchorsecurity.example'), 'active'),
((select id from public.associations where hoa_code = 'SR-10'), (select id from public.vendors where canonical_key = 'email:dispatch@coastlineplumb.example'), 'active'),
((select id from public.associations where hoa_code = 'SR-10'), (select id from public.vendors where canonical_key = 'email:service@aquapro.example'), 'active'),
((select id from public.associations where hoa_code = 'SR-12'), (select id from public.vendors where canonical_key = 'email:service@aquapro.example'), 'active')
on conflict do nothing;

insert into public.data_quality_flags (entity_type, entity_key, field_name, raw_value, cleaned_value, issue, severity) values
('association', 'SR-02', 'last_reserve_study', '04/2022', '2022-04-01', 'Month/year date stored as first day of month with month precision.', 'info'),
('association', 'SR-02', 'state', 'Calif.', 'CA', 'State normalized to postal code.', 'info'),
('association', 'SR-02', 'unit_count', '', NULL, 'Missing numeric value left null.', 'review'),
('association', 'SR-03', 'last_reserve_study', 'N/A', NULL, 'Missing date left null.', 'review'),
('association', 'SR-03', 'state', 'California', 'CA', 'State normalized to postal code.', 'info'),
('association', 'SR-03', 'reserve_balance', 'N/A', NULL, 'Missing or placeholder money value left null.', 'review'),
('association', 'SR-04', 'last_reserve_study', 'March 2024', '2024-03-01', 'Month/year date stored as first day of month with month precision.', 'info'),
('association', 'SR-06', 'last_reserve_study', '', NULL, 'Missing date left null.', 'review'),
('association', 'SR-06', 'state', 'ca', 'CA', 'State normalized to postal code.', 'info'),
('association', 'SR-06', 'unit_count', '', NULL, 'Missing numeric value left null.', 'review'),
('association', 'SR-06', 'monthly_dues', '$0', '0.00', 'Zero value retained but should be reviewed.', 'review'),
('association', 'SR-06', 'reserve_balance', 'TBD', NULL, 'Missing or placeholder money value left null.', 'review'),
('association', 'SR-09', 'last_reserve_study', 'N/A', NULL, 'Missing date left null.', 'review'),
('association', 'SR-09', 'reserve_balance', 'N/A', NULL, 'Missing or placeholder money value left null.', 'review'),
('association', 'SR-12', 'fiscal_year_end', '', NULL, 'Missing fiscal year end left null.', 'review'),
('board_member', 'SR-01:Reese Patel:Vice President', 'term_end', '', NULL, 'Missing date left null.', 'review'),
('board_member', 'SR-01:Alex Nguyen:Treasurer', 'email', '', NULL, 'Board member email missing.', 'review'),
('board_member', 'SR-02:Skyler Reyes:Secretary', 'email', '', NULL, 'Board member email missing.', 'review'),
('board_member', 'SR-03:Reese Patel:Treasurer', 'term_end', '', NULL, 'Missing date left null.', 'review'),
('board_member', 'SR-03:Reese Patel:Treasurer', 'email', '', NULL, 'Board member email missing.', 'review'),
('board_member', 'SR-03:Jordan Silva:Secretary', 'term_end', '', NULL, 'Missing date left null.', 'review'),
('board_member', 'SR-04:Drew Tanaka:Vice President', 'term_end', '', NULL, 'Missing date left null.', 'review'),
('board_member', 'SR-04:Riley Hughes:Treasurer', 'term_end', '', NULL, 'Missing date left null.', 'review'),
('board_member', 'SR-05:Riley Garcia:Vice President', 'term_end', '', NULL, 'Missing date left null.', 'review'),
('board_member', 'SR-05:Drew Cole:Secretary', 'email', '', NULL, 'Board member email missing.', 'review'),
('board_member', 'SR-06:Avery Tanaka:Vice President', 'term_end', '', NULL, 'Missing date left null.', 'review'),
('board_member', 'SR-06:Avery Tanaka:Vice President', 'email', '', NULL, 'Board member email missing.', 'review'),
('board_member', 'SR-07:Skyler Garcia:President', 'term_end', '', NULL, 'Missing date left null.', 'review'),
('board_member', 'SR-07:Jamie Nguyen:Vice President', 'term_end', '', NULL, 'Missing date left null.', 'review'),
('board_member', 'SR-07:Jamie Nguyen:Vice President', 'email', '', NULL, 'Board member email missing.', 'review'),
('board_member', 'SR-07:Avery Cole:Member at Large', 'term_end', '', NULL, 'Missing date left null.', 'review'),
('board_member', 'SR-08:Morgan Hughes:President', 'term_end', '', NULL, 'Missing date left null.', 'review'),
('board_member', 'SR-08:Sam Webb:Vice President', 'term_end', '', NULL, 'Missing date left null.', 'review'),
('board_member', 'SR-09:Devon Reyes:President', 'term_end', '', NULL, 'Missing date left null.', 'review'),
('board_member', 'SR-09:Devon Reyes:President', 'email', '', NULL, 'Board member email missing.', 'review'),
('board_member', 'SR-09:Avery Cole:Vice President', 'term_end', '', NULL, 'Missing date left null.', 'review'),
('board_member', 'SR-10:Jordan Webb:President', 'term_end', '', NULL, 'Missing date left null.', 'review'),
('board_member', 'SR-11:Riley Cole:Vice President', 'term_end', '', NULL, 'Missing date left null.', 'review'),
('board_member', 'SR-11:Casey Brooks:Member at Large', 'term_end', '', NULL, 'Missing date left null.', 'review'),
('board_member', 'SR-12:Casey Brooks:President', 'term_end', '', NULL, 'Missing date left null.', 'review'),
('board_member', 'SR-12:Casey Brooks:President', 'email', '', NULL, 'Board member email missing.', 'review'),
('board_member', 'SR-12:Harper Okafor:Vice President', 'term_end', '', NULL, 'Missing date left null.', 'review'),
('board_member', 'SR-01:Alex Tanaka:President', 'row', '{''hoa_code'': ''SR-01'', ''full_name'': ''Alex Tanaka'', ''role'': ''President'', ''email'': ''alex.tanaka@example.com'', ''term_start'': ''2023-07-01'', ''term_end'': ''2025-07-01''}', 'deduplicated', 'Exact duplicate board member row removed.', 'info'),
('vendor', 'email:hello@evergreentree.example', 'serves_hoa_codes', '', NULL, 'Intake row has no linked HOA; vendor retained as prospect if no other row links it.', 'info'),
('vendor', 'email:jobs@summitroof.example', 'serves_hoa_codes', '', NULL, 'Intake row has no linked HOA; vendor retained as prospect if no other row links it.', 'info'),
('vendor', 'email:office@reliableelec.example', 'coi_on_file', '', NULL, 'COI value missing or unparseable.', 'review'),
('vendor', 'email:office@reliableelec.example', 'serves_hoa_codes', '', NULL, 'Intake row has no linked HOA; vendor retained as prospect if no other row links it.', 'info'),
('vendor', 'email:book@greenleafpest.example', 'serves_hoa_codes', '', NULL, 'Intake row has no linked HOA; vendor retained as prospect if no other row links it.', 'info'),
('vendor', 'email:info@clearviewwc.example', 'serves_hoa_codes', '', NULL, 'Intake row has no linked HOA; vendor retained as prospect if no other row links it.', 'info'),
('vendor', 'email:contact@brightpathscapes.example', 'serves_hoa_codes', 'SR-01', 'SR-01', 'Duplicate vendor-HOA relationship removed.', 'info'),
('vendor', 'email:contact@brightpathscapes.example', 'vendor_name', 'Bright Path Landscaping; Bright Path Landscaping LLC', 'Bright Path Landscaping', 'Vendor aliases merged because rows shared email or phone/trade.', 'info'),
('vendor', 'email:hello@evergreentree.example', 'relationship_status', NULL, 'prospect', 'Vendor has no HOA relationship and is retained as a prospect.', 'info'),
('vendor', 'email:jobs@summitroof.example', 'relationship_status', NULL, 'prospect', 'Vendor has no HOA relationship and is retained as a prospect.', 'info'),
('vendor', 'email:office@reliableelec.example', 'vendor_name', 'Reliable Electric; Reliable Electrical Services', 'Reliable Electric', 'Vendor aliases merged because rows shared email or phone/trade.', 'info'),
('vendor', 'email:book@greenleafpest.example', 'relationship_status', NULL, 'prospect', 'Vendor has no HOA relationship and is retained as a prospect.', 'info'),
('vendor', 'email:info@clearviewwc.example', 'relationship_status', NULL, 'prospect', 'Vendor has no HOA relationship and is retained as a prospect.', 'info');
