create extension if not exists citext;

create table if not exists public.associations (
    id bigint generated by default as identity primary key,
    hoa_code text not null unique check (hoa_code ~ '^SR-[0-9]{2}$'),
    association_name text not null,
    city text not null,
    state_code char(2) not null check (state_code ~ '^[A-Z]{2}$'),
    unit_count integer check (unit_count is null or unit_count > 0),
    monthly_dues numeric(10,2) check (monthly_dues is null or monthly_dues >= 0),
    fiscal_year_end_month smallint check (
        fiscal_year_end_month is null or fiscal_year_end_month between 1 and 12
    ),
    reserve_balance numeric(14,2) check (
        reserve_balance is null or reserve_balance >= 0
    ),
    last_reserve_study date,
    last_reserve_study_precision text not null default 'unknown'
        check (last_reserve_study_precision in ('day', 'month', 'unknown')),
    has_reserve_study boolean not null default false,
    board_email citext,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create table if not exists public.board_members (
    id bigint generated by default as identity primary key,
    association_id bigint not null references public.associations(id) on delete cascade,
    full_name text not null,
    role text not null,
    email citext,
    term_start date,
    term_end date,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    check (term_end is null or term_start is null or term_end >= term_start)
);

create unique index if not exists board_members_natural_key
    on public.board_members (
        association_id,
        lower(full_name),
        lower(role),
        coalesce(term_start, date '1900-01-01')
    );

create table if not exists public.vendors (
    id bigint generated by default as identity primary key,
    canonical_key text not null unique,
    canonical_name text not null,
    trade text not null,
    phone_e164 text,
    phone_display text,
    email citext,
    coi_on_file boolean,
    service_area text[] not null default '{}',
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create index if not exists vendors_trade_idx on public.vendors (trade);
create index if not exists vendors_email_idx on public.vendors (email);

create table if not exists public.vendor_aliases (
    id bigint generated by default as identity primary key,
    vendor_id bigint not null references public.vendors(id) on delete cascade,
    alias_name text not null,
    source_file text not null default 'vendors_intake.csv',
    created_at timestamptz not null default now()
);

create unique index if not exists vendor_aliases_vendor_alias_key
    on public.vendor_aliases (vendor_id, lower(alias_name));

create table if not exists public.association_vendors (
    association_id bigint not null references public.associations(id) on delete cascade,
    vendor_id bigint not null references public.vendors(id) on delete cascade,
    relationship_status text not null default 'active'
        check (relationship_status in ('active', 'prospect', 'inactive')),
    source_file text not null default 'vendors_intake.csv',
    created_at timestamptz not null default now(),
    primary key (association_id, vendor_id)
);

create table if not exists public.data_quality_flags (
    id bigint generated by default as identity primary key,
    entity_type text not null,
    entity_key text not null,
    field_name text not null,
    raw_value text,
    cleaned_value text,
    issue text not null,
    severity text not null default 'review'
        check (severity in ('info', 'review', 'warning')),
    created_at timestamptz not null default now()
);

create index if not exists data_quality_flags_entity_idx
    on public.data_quality_flags (entity_type, entity_key);

create or replace view public.association_vendor_counts as
select
    a.id as association_id,
    a.hoa_code,
    v.trade,
    count(*)::integer as vendor_count
from public.associations a
join public.association_vendors av on av.association_id = a.id
join public.vendors v on v.id = av.vendor_id
group by a.id, a.hoa_code, v.trade;
